<?php

function cipher_menu() {
  $items['cipher'] = array(
    'title' => 'Caesarean cipher',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cipher_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['cipher_success_page'] = array(
    'title' => 'Encoded',
    'page callback' => 'cipher_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function cipher_form(){
  $form['shift_value'] = array(
    '#title' => 'shift value',
    '#type' => 'textfield',
    '#description' => t('Please enter by how spaces to shift each letter'),
    '#element_validate' => array('element_validate_integer_positive'),
    '#required' => TRUE,

  );

  $form['direction'] = array(
    '#title' => 'direction',
    '#type' => 'textfield',
    '#description' => t('Please choose in-which direction, either left or right, to shift the letters.'),
    '#element_validate' => array('element_validate_direction'),
    '#required' => TRUE,

  );

  $form['phrase'] = array(
    '#title' => 'phrase',
    '#type' => 'textfield',
    '#description' => t('Please a phrase to encrypt'),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#value' => 'Encrypt now!',
    '#type' => 'submit',
  );

  return $form;
  }

  function element_validate_direction($element) {
    if (!($element ['#value'] == "left" || $element['#value'] == "right")) {
        form_error($element, t('Its cases sensitive, so please only eneter in "left" or "right" for the direction.'));
    }
  }

  function cipher_phrase($input_phrase, $shift, $direction) {
      $input_array = str_split($input_phrase);
      $output_array = array();
      foreach ($input_array as $input_letter) {
          if (preg_match("/[a-zA-Z]/", $input_letter)) {
              $output_array[] = cipher_letter($input_letter, $shift, $direction);
          } else {
              $output_array[] = $input_letter;
          }
      }
      return join("", $output_array);
    }

  function cipher_letter($input_letter, $shift, $direction) {
    $alpha = "abcdefghijklmnopqrstuvwxyz";
    $shift = $direction == "right" ? $shift : -$shift;
    $position_orig = stripos($alpha, strtolower($input_letter));
    $position_new = $position_orig + $shift + 26;
    $position_new = $position_new % 26;

    return $alpha[(int)$position_new];
  }

  function cipher_form_submit($form, &$form_state){
    $shift_value = $form_state['values']['shift_value'];
    $direction = $form_state['values']['direction'];
    $phrase = $form_state['values']['phrase'];
    $encrypted_phrase = cipher_phrase($phrase, $shift_value, $direction);
    $_SESSION['cipher_shift_value'] = $shift_value;
    $_SESSION['cipher_direction'] = $direction;
    $_SESSION['cipher_phrase'] = $phrase;
    $_SESSION['cipher_output'] = $encrypted_phrase;
    $form_state['redirect'] = 'cipher_success_page';
  }

  function cipher_success(){
    $shift_value = $_SESSION['cipher_shift_value'];
    $direction = $_SESSION['cipher_direction'];
    $phrase = $_SESSION['cipher_phrase'];
    $answer = $_SESSION['cipher_output'];
    $display_result = 'encrypted your phrase, <br>';
    $display_result .= '<strong>' . $phrase . '</strong><br> by shifting ' . $shift_value . ' to the ' . $direction . ' with the following result:<br>';
    $display_result .= '<strong>' . $answer . '</strong>';
    return $display_result;
  }
