<?php


function cipher_menu() {
  $items = array();
  $items['caesarean_cipher'] = array(
    'title' => 'Caesarean cipher',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('caesarean_cipher_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['caesarean_cipher_success'] = array(
    'title' => 'Encoded',
    'page callback' => 'caesarean_cipher_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function caesarean_cipher_form(){
  $form['shift_value'] = array(
    '#title' => 'shift value',
    '#type' => 'textfield',
    '#element_validate' =>
    array('element_validate_int_positive'),
      '#description' => t('Please enter by how spaces to shift each letter'),
  );

  $form['direction'] = array(
    '#title' => 'direction',
    '#type' => 'textfield',
    '#element_validate' => array('element_validate_proper_direction'),
    '#description' => t('Please choose in a direction, either left or right in-which to shift the letters.'),
  );

  $form['phrase'] = array(
    '#title' => 'phrase',
    '#type' => 'textfield',
    '#element_validate' => array('element_validate_proper_phrase'),
    '#description' => t('Please a phrase to encrypt'),
  );

  $form['submit'] = array(
    '#value' => 'Encrypt now!',
    '#type' => 'submit',
  );

  return $form;
  }

  // function caesarean_cipher_form_submit($form, &$form_state){
  //   $shift_value = $_SESSION['shift_value'] = $form_state['values']['shift_vlaue'];
  //   $direction = $_SESSION['direction'] = $form_state['values']['direction'];
  //   $phrase = $_SESSION['phrase'] = $form_state['values']['phrase'];
  //
  //   $_SESSION['encrypted_phrase'] =
  //
  // }
